version: 2.1

executors:
  default_build_environment:
    docker:
      - image: cimg/node:19.3
        auth:
          username: codainternaltools
          password: $DOCKERHUB_PASSWORD

jobs:
  build:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: 'Install deps'
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: 'Compile'
          command: npm run compile
      - run:
          name: 'Lint'
          command: npm run lint
      - run:
          name: 'Validate'
          command: npm run validate

workflows:
  version: 2
  commit_validation:
    jobs:
      - build:
          context:
            - dockerhub
