version: 2.1

executors:
  default_build_environment:
    docker:
      - image: cimg/node:14.13
        auth:
          username: codainternaltools
          password: $DOCKERHUB_PASSWORD

jobs:
  build:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run:
          name: 'Install deps'
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Compile'
          command: npm run compile

workflows:
  version: 2
  commit_validation:
    jobs:
      - build:
          context:
            - dockerhub
